export const soundCloudProfile = {
  title: "Koi Boi Official Music (All)",
  url: "https://soundcloud.com/koi-boi",
  count: 78,
};

export const tracks = [
  { title: "Koi Boi - Acid Portal", url: "https://soundcloud.com/koi-boi/koi-boi-acid-portal", type: "Track" },
  { title: "KoiBoi & Brainwash -Time Portal", url: "https://soundcloud.com/koi-boi/koiboi-brainwash-time-portal-2", type: "Track" },
  { title: "KoiBoi-Moonspo", url: "https://soundcloud.com/koi-boi/koiboi-moonspo", type: "Track" },
  { title: "KoiBoi -Pregmatix -Lucid Mask", url: "https://soundcloud.com/koi-boi/koiboi-pregmatix-lucid-mask", type: "Track" },
  { title: "KoiBoi-Modular Reality .", url: "https://soundcloud.com/koi-boi/sets/koiboi-modular-reality", type: "Set" },
  { title: "KoiBoi-Modular Reality . master", url: "https://soundcloud.com/koi-boi/16fc0ce1-7f1a-4324-8af1-fe2709dbb79a", type: "Track" },
  { title: "KoiBoi-Psychoactive master", url: "https://soundcloud.com/koi-boi/3e098621-c4df-4999-9b70-be18f28e463d", type: "Track" },
  { title: "KoiBoi -What You Say", url: "https://soundcloud.com/koi-boi/koiboi-what-you-say", type: "Track" },
  { title: "X-noize, KoIBoi - Multiverse", url: "https://soundcloud.com/koi-boi/x-noize-koiboi-multiverse", type: "Track" },
  { title: "KoiBoi", url: "https://soundcloud.com/koi-boi/sets/koiboi", type: "Set" },
  { title: "Koi Boi & X-noiZe- The Lab (out now)", url: "https://soundcloud.com/koi-boi/koi-boi-x-noize-the-lab-out-now", type: "Track" },
  { title: "Koi Boi - Knowledge Is The Key ( Synthwave Records)", url: "https://soundcloud.com/koi-boi/koi-boi-knowledge-is-the-key", type: "Track" },
  { title: "01 - Koi Boi - Shadow Of The Tribe ( Synthwave Records)", url: "https://soundcloud.com/koi-boi/01-koi-boi-shadow-of-the-tribe-synthwave-records", type: "Track" },
  { title: "KoiBoi Shaman Boom (Morion Records) OUT NOW", url: "https://soundcloud.com/koi-boi/koiboi-shaman-boom", type: "Track" },
  { title: "A2Z (Original Mix)", url: "https://soundcloud.com/koi-boi/a2z-original-mix", type: "Track" },
  { title: "Koi Boi & Ashagra - A2z (now Soon) Morion Records)", url: "https://soundcloud.com/koi-boi/koi-boi-ashagra-a2z-out-now-morion-records", type: "Track" },
  { title: "KoiBoi fish Man Nutek Record (OUT NOW)", url: "https://soundcloud.com/koi-boi/koiboi-fhis-man-nutek-rac-out-now", type: "Track" },
  { title: "X - NoiZe & Koi Boi - Human Perception(OUT NOW)", url: "https://soundcloud.com/koi-boi/x-noize-koi-boi-human-perceptionout-now", type: "Track" },
  { title: "- Koi Boi - Magic Mushrooms (Original Mix)", url: "https://soundcloud.com/koi-boi/sets/koi-boi-magic-mushrooms", type: "Set" },
  { title: "Koi Boi - Everything Is Everything (Original Mix)", url: "https://soundcloud.com/koi-boi/koi-boi-everything-is-everything-original-mix", type: "Track" },
  { title: "Koi Boi - Magic Mushroom (Original Mix)", url: "https://soundcloud.com/koi-boi/koi-boi-magic-mushroom-original-mix", type: "Track" },
  { title: "Koi Boi - Play By The Rules // FULL TRACK // OUT NOW! (Synthwave Rec.)", url: "https://soundcloud.com/koi-boi/play-by-the-rules", type: "Track" },
  { title: "KOIBOI -ACID PINPONG -EP (Morion Records)", url: "https://soundcloud.com/koi-boi/sets/koiboi-acid-pinpong-ep-morion", type: "Set" },
  { title: "KoiBoi - We From Energy (Out now) Morion Records)", url: "https://soundcloud.com/koi-boi/koiboi-we-from-energy-out-soon-morion-records", type: "Track" },
  { title: "KOIBOI- ACID PINPONG (Out now) Morion Records)", url: "https://soundcloud.com/koi-boi/koiboi-acid-pinpong-out-soon-morion-records", type: "Track" },
  { title: "Koi Boi - Everything Is Different (out now)iono music", url: "https://soundcloud.com/koi-boi/koi-boi-everything-is-different-out-ssoniono-music", type: "Track" },
  { title: "Koi Boi - SUMMER MIX 2018 (Free download)", url: "https://soundcloud.com/koi-boi/koi-boi-summer-mix-2018", type: "Track" },
  { title: "*SHAMANIC DREAM* ALBUM MIX(United Beats Records)", url: "https://soundcloud.com/koi-boi/shamanic-dream-album-mixunited-beats-records", type: "Track" },
  { title: "SHAMANIC DREAM ALBUM (United Beats Records)", url: "https://soundcloud.com/koi-boi/sets/shamanic-dream-album-1", type: "Set" },
  { title: "1. Shamanic Dream", url: "https://soundcloud.com/koi-boi/1-shamanic-dream", type: "Track" },
  { title: "2. Future Dimension", url: "https://soundcloud.com/koi-boi/2-2-future-dimension-1", type: "Track" },
  { title: "3.God", url: "https://soundcloud.com/koi-boi/3-god", type: "Track" },
  { title: "4.Play By The Rules", url: "https://soundcloud.com/koi-boi/4-play-by-the-rules-16bit", type: "Track" },
  { title: "5.Beyond Destiny", url: "https://soundcloud.com/koi-boi/5-beyond-destiny", type: "Track" },
  { title: "6.Teleportation", url: "https://soundcloud.com/koi-boi/6-teleportation", type: "Track" },
  { title: "7.The Last Question", url: "https://soundcloud.com/koi-boi/7-the-last-question", type: "Track" },
  { title: "Back to the square", url: "https://soundcloud.com/koi-boi/8-back-to-the-square", type: "Track" },
  { title: "9.Higher Consciousness", url: "https://soundcloud.com/koi-boi/9-higher-consciousness", type: "Track" },
  { title: "10. Elephant On Acid", url: "https://soundcloud.com/koi-boi/10-elephant-on-acid", type: "Track" },
  { title: "Koi Boi - Universo Paralello / 01.01.2018 Free download", url: "https://soundcloud.com/koi-boi/koi-boi-universo-paralello-01012018-free-download", type: "Track" },
  { title: "Koi Boi Live Radio Ozora 2017(United BeatsRecords)", url: "https://soundcloud.com/koi-boi/koi-boi-live-radio-ozora-2017", type: "Track" },
  { title: "Koi Boi - Higher Consciousness (E.P OUT NOW) unitedbeats Record)", url: "https://soundcloud.com/koi-boi/sets/koi-boi-higher-consciousness", type: "Set" },
  { title: "Mad Max - Knob Job ( Koi Boi Remix)(E.P)", url: "https://soundcloud.com/koi-boi/mad-max-knob-job-koi-boi-remix", type: "Track" },
  { title: "Koi Boi - Higher Consciousness (E.P)", url: "https://soundcloud.com/koi-boi/koi-boi-higher-consciousness", type: "Track" },
  { title: "Koi Boi E.P Roots (IONO MUISC)", url: "https://soundcloud.com/koi-boi/sets/koi-boi-e-p-roots-iono-muisc", type: "Set" },
  { title: "Koi Boi - The Music Makers Out Now (IONO MUSIC)", url: "https://soundcloud.com/koi-boi/koi-boi-the-music-makers-out-now-iono-music", type: "Track" },
  { title: "Koi Boi - In A Dream Out Now (IONO MUSIC )", url: "https://soundcloud.com/koi-boi/koi-boi-in-a-dream-out-now-iono-music", type: "Track" },
  { title: "Koi Boi - Universe Speed (E,P) HOMmega official", url: "https://soundcloud.com/koi-boi/sets/koi-boi-universe-speed-e-p", type: "Set" },
  { title: "Freedom Fighters & Avalon - Twist N' Turns (Koi Boi Remix)", url: "https://soundcloud.com/koi-boi/freedom-fighters-avalon-twist-n-turns-koi-boi-remix", type: "Track" },
  { title: "Koi Boi Universe Speed", url: "https://soundcloud.com/koi-boi/koi-boi-universe-speed", type: "Track" },
  { title: "Koi Boi & Ranji - \"Chaos\" HOMmega official", url: "https://soundcloud.com/koi-boi/ranji-vs-koi-boi-chaoss", type: "Track" },
  { title: "Koi Boi The matrix @ United Beats Records", url: "https://soundcloud.com/koi-boi/koi-boi-the-matrixx-preview-out-soon-united-beats-records", type: "Track" },
  { title: "Good Fortune E.P All Rec (Free Download)", url: "https://soundcloud.com/koi-boi/sets/good-fortune", type: "Set" },
  { title: "Koi Boi Beautiful Subject", url: "https://soundcloud.com/koi-boi/koi-boi-beautiful-subject", type: "Track" },
  { title: "Koi Boi - RadiOzora DJ SET 22/02/2014 (Free Download)", url: "https://soundcloud.com/koi-boi/koi-boi-radiozora-live-set-22", type: "Track" },
  { title: "Koi Boi -E.p Element (Phantasm Records) Free Download", url: "https://soundcloud.com/koi-boi/sets/koi-boi-e-p-element-phantasm", type: "Set" },
  { title: "Koi Boi-Survive", url: "https://soundcloud.com/koi-boi/koi-boi-survive", type: "Track" },
  { title: "Vertical mode-lucky number (Koi Boi Rmx) Free Download", url: "https://soundcloud.com/koi-boi/vertical-mode-lucky-number-ko", type: "Track" },
  { title: "Koi Boi-Elements New Edit", url: "https://soundcloud.com/koi-boi/koi-boi-elements-new-edit", type: "Track" },
  { title: "Koi Boi-Pc Pitch ..Free Download", url: "https://soundcloud.com/koi-boi/koi-boi-pc-pitch", type: "Track" },
  { title: "Koi Boi (E.P) \"Other Direction\" (Free Download)", url: "https://soundcloud.com/koi-boi/sets/koi-boi-e-p-other-direction", type: "Set" },
  { title: "Koi Boi Mini Mix (2013) Free Download", url: "https://soundcloud.com/koi-boi/koi-boi-mini-mix-2013-free", type: "Track" },
  { title: "Koi Boi - Sound of Silence * E.P (( All Rec ))", url: "https://soundcloud.com/koi-boi/koi-boi-sound-of-silence-e-p", type: "Track" },
  { title: "Koi Boi - E.P -Power of the Samurai [All Records]", url: "https://soundcloud.com/koi-boi/sets/koo-boi", type: "Set" },
  { title: "Koi Bo i Vs BrightLight - Fundemental idea E.P (( All Rec ))", url: "https://soundcloud.com/koi-boi/koi-bo-i-vs-brightlight", type: "Track" },
  { title: "KOI BOI *Alien Race* E.P (( All Rec ))", url: "https://soundcloud.com/koi-boi/koi-boi-new-demo-16-t", type: "Track" },
  { title: "Koi Boi E,P - Swimming With Sharks (Trancelucent Productions)", url: "https://soundcloud.com/koi-boi/sets/new-e-p-2012-trancelucent-1", type: "Set" },
  { title: "Koi Boi Sound Vallley @EP@ Trancelucent Records", url: "https://soundcloud.com/koi-boi/koi-boi-sound-vallley-ep", type: "Track" },
  { title: "Koi Boi -Want You Back (E.P) \"Other Direction\"", url: "https://soundcloud.com/koi-boi/koi-boi-want-you-back-e-p", type: "Track" },
  { title: "NEW E.P The Big Blue Trancelucent Records", url: "https://soundcloud.com/koi-boi/sets/new-e-p-2012-trancelucent", type: "Set" },
  { title: "Koi Boi vs Solarix - Magic Space *Free* download.@EP@ Synergetic Records", url: "https://soundcloud.com/koi-boi/koi-boi-vs-solarix-magic-space", type: "Track" },
  { title: "Koi Boi-Magnetic *Free* download.@EP@ Trancelucent Records", url: "https://soundcloud.com/koi-boi/koi-boi-magnetic-free-download", type: "Track" },
  { title: "KOI BOI GROOVE CITY (E.P) \"Other Direction\"", url: "https://soundcloud.com/koi-boi/koi-boi-groove-city-promo", type: "Track" },
  { title: "Koi Boi- Ritmologic E.P (( All Rec ))", url: "https://soundcloud.com/koi-boi/koi-boi-ritmo-logic-preview", type: "Track" },
  { title: "Koi Boi-Key to unlock the Door.@EP@ Trancelucent Records", url: "https://soundcloud.com/koi-boi/key", type: "Track" },
  { title: "Koi Boi-This is a journey@EP@ Trancelucent Records", url: "https://soundcloud.com/koi-boi/envelope-this-is-a-journey", type: "Track" },
  { title: "Koi Boi-PARALLEL UNIVERSE @EP@ Trancelucent Records", url: "https://soundcloud.com/koi-boi/universal-no", type: "Track" },
  { title: "Koi Boi-EnJoy This Trip @EP@ Trancelucent Records", url: "https://soundcloud.com/koi-boi/envelope-enjoy-this-trip", type: "Track" },
] as const;
